import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Bookit App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.className} antialiased container mx-auto`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Header/>
        {children}
        <Footer />
        <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
